# Generated by Django 5.2.8 on 2025-12-07 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='appointmentslot',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created',
        ),
    ]
