# Generated by Django 5.2.8 on 2025-12-07 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentslot',
            name='max_capacity',
        ),
    ]
