# Generated by Django 5.2.8 on 2025-12-02 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_booking_user_alter_booking_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
    ]
