# Generated by Django 5.2.8 on 2025-12-03 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_booking_email_remove_booking_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentslot',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
